# Generated by Django 2.2 on 2019-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('AS', 'ArtSale'), ('AW', 'ArtWork')], default='AW', max_length=15),
        ),
    ]
