# Generated by Django 2.2 on 2019-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0002_obra_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
