# Generated by Django 2.2 on 2019-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0004_auto_20190525_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
