# Generated by Django 2.2 on 2019-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0005_auto_20190525_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='archivos',
            field=models.FileField(null=True, upload_to='archivos/'),
        ),
    ]
