# Generated by Django 2.2 on 2019-05-26 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0006_obra_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='archivos',
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ObraArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('obra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='symbiarts_app.Obra')),
            ],
        ),
    ]
