# Generated by Django 2.2 on 2019-05-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0007_auto_20190526_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obraarchivo',
            old_name='obra_id',
            new_name='obra',
        ),
    ]
