# Generated by Django 2.2 on 2019-06-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0011_auto_20190605_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
