# Generated by Django 2.2 on 2019-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0012_auto_20190605_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
