# Generated by Django 2.2 on 2019-07-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0014_detalleventaobra_metodopago_ventaobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='pausada',
            field=models.BooleanField(default=False),
        ),
    ]
