# Generated by Django 2.2 on 2019-07-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0015_obra_pausada'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fecha_pausada',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
