# Generated by Django 2.2.2 on 2019-07-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0016_obra_fecha_pausada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_pausada',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
