# Generated by Django 2.2 on 2019-07-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0016_obra_fecha_pausada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_pausada',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ventaobra',
            name='metodo_pago',
            field=models.TextField(default='credit_card', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
