# Generated by Django 2.2 on 2019-08-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0017_auto_20190715_1731'),
        ('symbiarts_app', '0017_auto_20190729_2148'),
    ]

    operations = [
    ]
