# Generated by Django 2.2 on 2019-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiarts_app', '0019_auto_20190817_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaobra',
            name='id_pago',
            field=models.BigIntegerField(),
        ),
    ]
