# Generated by Django 2.2 on 2019-08-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('symbiarts_app', '0020_auto_20190817_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='usuario',
            new_name='artista',
        ),
        migrations.RemoveField(
            model_name='detalleventaobra',
            name='obra',
        ),
        migrations.AddField(
            model_name='detalleventaobra',
            name='obra_artista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventaobra',
            name='obra_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventaobra',
            name='obra_nombre',
            field=models.CharField(default='nombre obra', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventaobra',
            name='obra_url_imagen',
            field=models.CharField(default='url', max_length=100),
            preserve_default=False,
        ),
    ]
